# Generated by Django 4.2.13 on 2024-05-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=255, verbose_name='Montant')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
            ],
            options={
                'verbose_name': 'Amande',
                'verbose_name_plural': 'Amandes',
            },
        ),
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('gps_location', models.CharField(max_length=255, verbose_name='Localisation GPS')),
            ],
            options={
                'verbose_name': 'Point de contrôle',
                'verbose_name_plural': 'Points de contrôle',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Critère',
                'verbose_name_plural': 'Critères',
            },
        ),
        migrations.CreateModel(
            name='CriteriaByControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, verbose_name='État')),
                ('almond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.almond', verbose_name='Amande')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.criteria')),
            ],
            options={
                'verbose_name': 'Critère par contrôle',
                'verbose_name_plural': 'Critères par contrôle',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone_number', models.CharField(max_length=255, unique=True, verbose_name='Numéro de téléphone')),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé à')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour à')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé à')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur personnalisé',
                'verbose_name_plural': 'Utilisateurs personnalisés',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone_number', models.CharField(max_length=255, unique=True, verbose_name='Numéro de téléphone')),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé à')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour à')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé à')),
                ('license_number', models.CharField(max_length=255, verbose_name='Numéro du permis')),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=255, verbose_name='Immatriculation')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.customuser')),
                ('matricule', models.CharField(max_length=255, verbose_name='Matricule')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('api.customuser',),
        ),
        migrations.CreateModel(
            name='RoadControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controlpoint')),
                ('criteria', models.ManyToManyField(through='api.CriteriaByControl', to='api.criteria')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
            ],
            options={
                'verbose_name': 'Contrôle routier',
                'verbose_name_plural': 'Contrôles routiers',
            },
        ),
        migrations.AddField(
            model_name='criteriabycontrol',
            name='road_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roadcontrol'),
        ),
        migrations.AlterUniqueTogether(
            name='criteriabycontrol',
            unique_together={('criteria', 'road_control')},
        ),
        migrations.CreateModel(
            name='ControlPointByAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, verbose_name='État')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controlpoint')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
            ],
            options={
                'verbose_name': 'Point de contrôle par agent',
                'verbose_name_plural': 'Points de contrôle par agents',
                'unique_together': {('agent', 'control_point')},
            },
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='agents',
            field=models.ManyToManyField(through='api.ControlPointByAgent', to='api.agent'),
        ),
    ]
