# Generated by Django 4.2.13 on 2024-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpointbyagent',
            name='state',
            field=models.BooleanField(max_length=255, verbose_name='État'),
        ),
    ]
