# Generated by Django 4.2.13 on 2024-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_controlpointbyagent_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcontrol',
            name='date',
            field=models.DateField(default='now()', verbose_name='Date'),
        ),
    ]
