# Generated by Django 4.2.13 on 2024-05-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_roadcontrol_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriabycontrol',
            name='almond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.almond', verbose_name='Amande'),
        ),
    ]
